### ISSUE TITLE
Stworzenie klasy głównej

### ISSUE THREAD

**Issue by Goslawq** [Goslawq/text-transformer#2]
Klasa parsująca żądania przetworzeń, wywołująca poklasy przetwarzające

**Comment by czplwsk** [comment]
Zrobione wstępnie, nie zamykam bo będą wchodzić updates na pewno wraz ze stworzeniem kolejnych klas.

**Comment by czplwsk** [comment]
Reopened, because needs modifications.

**Comment by Goslawq** [comment]
Potrzeba zmienić sposób przyjmowania stringa na taki który nie zawiera <>, ponieważ interferują one z generacją dokumentacji

**Comment by czplwsk** [comment]
Done
