### ISSUE TITLE
Klasa do zmiany wielkości liter

### ISSUE THREAD

**Issue by Goslawq** [Goslawq/text-transformer#3]
Jako użytkownik mogę zmianać wielkości liter – zestaw trzech transformacji (upper, lower, capitalize)

**Comment by czplwsk** [comment]
Klasa zrobiona

**Comment by Goslawq** [comment]
Capitalize działa niepoprawnie, powinna zwiększać pierwszy znak każdego wyrazu a nie tylko pierwszego

**Comment by czplwsk** [comment]
Fixed
